# image: $CI_REGISTRY_IMAGE/taste:latest
image: taste-buster:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - post_build

build:
  stage: build
  script:
    - ./configure ; pip3 install -r requirements.txt ; cd / ; wget -q -O - https://github.com/ttsiodras/asn1scc/releases/download/4.3.0.0/asn1scc-bin-4.3.0.0.tar.bz2 | tar jxpvf - ; cd - ; LANG=C LC_ALL=C PATH=$PATH:/asn1scc:/root/.local/bin/ make
  # artifacts:
    # paths:
    #   - 'test/logs/*.err.txt'
    # when: on_failure
    # expire_in: 2 weeks
