version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          key: docker-{{ checksum "Dockerfile" }}
      - run:
          # command: if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; else docker build -t dmt . && { mkdir -p ~/docker; docker save dmt > ~/docker/image.tar ; } ; fi
          command: docker build -t dmt . && { mkdir -p ~/docker; docker save dmt > ~/docker/image.tar ; }
      - save_cache:
          key: docker-{{ checksum "Dockerfile" }}
          paths:
            - ~/docker
      - run:
          command: docker run -it -v $(pwd):/root/tests dmt bash -c 'cd /root/tests ; pip3 uninstall dmt ; ./configure ; pip3 install --upgrade . ; export CIRCLECI=1  ; LANG=C LC_ALL=C PATH=$PATH:/asn1scc make'
